name: CI1

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 您可以使用 '3.6' 來指定特定版本

    - name: Install PyTorch and TensorBoard
      run: |
        pip install torch==1.4.0 torchvision==0.5.0 torchaudio==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html
        pip install tensorboard
        pip install protobuf==3.20
        pip install numpy==1.19.5

#    - name: Run Deeplog
#      run: |
#        python LogKeyModel_train.py
